package View;

import DAO.ProductDAO;
import Model.Product;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bispo
 */
public class EditProduct extends javax.swing.JFrame {

    /**
     * Creates new form EditProduct
     */
    public EditProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescription = new javax.swing.JTextField();
        txtSku = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtEan = new javax.swing.JTextField();
        btnConfirmEdit = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnCancelEdit = new javax.swing.JButton();
        chkStatus = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        txtDescription.setBackground(new java.awt.Color(161, 131, 239));
        txtDescription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(255, 255, 255));
        txtDescription.setBorder(null);
        txtDescription.setPreferredSize(new java.awt.Dimension(81, 25));
        getContentPane().add(txtDescription);
        txtDescription.setBounds(30, 260, 980, 70);

        txtSku.setBackground(new java.awt.Color(161, 131, 239));
        txtSku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSku.setForeground(new java.awt.Color(255, 255, 255));
        txtSku.setBorder(null);
        getContentPane().add(txtSku);
        txtSku.setBounds(30, 370, 460, 70);

        txtPrice.setBackground(new java.awt.Color(161, 131, 239));
        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtPrice.setBorder(null);
        getContentPane().add(txtPrice);
        txtPrice.setBounds(510, 370, 270, 70);

        txtQuantity.setBackground(new java.awt.Color(161, 131, 239));
        txtQuantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantity.setBorder(null);
        getContentPane().add(txtQuantity);
        txtQuantity.setBounds(800, 370, 211, 70);

        txtEan.setBackground(new java.awt.Color(161, 131, 239));
        txtEan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEan.setForeground(new java.awt.Color(255, 255, 255));
        txtEan.setBorder(null);
        getContentPane().add(txtEan);
        txtEan.setBounds(30, 480, 980, 70);

        btnConfirmEdit.setContentAreaFilled(false);
        btnConfirmEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfirmEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmEdit);
        btnConfirmEdit.setBounds(300, 640, 220, 50);
        getContentPane().add(txtId);
        txtId.setBounds(40, 150, 90, 40);

        btnCancelEdit.setContentAreaFilled(false);
        btnCancelEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelEdit);
        btnCancelEdit.setBounds(570, 640, 210, 50);

        chkStatus.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        chkStatus.setForeground(new java.awt.Color(255, 255, 255));
        chkStatus.setText("STATUS");
        getContentPane().add(chkStatus);
        chkStatus.setBounds(900, 150, 110, 45);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DESCRIÇÃO:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 230, 140, 30);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("SKU:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 340, 60, 30);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PREÇO:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(510, 340, 80, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("QUANTIDADE:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(800, 340, 160, 30);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("EAN:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 450, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EditProduct.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1080, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmEditActionPerformed
        String description, ean, sku;
        double price;
        int quantity, id;
        boolean status;
        
        if (chkStatus.isSelected()) {
            status = true;
        } else {
            status = false;
        }
        
        description = txtDescription.getText();
        ean = txtEan.getText();
        sku = txtSku.getText();
        price = Double.parseDouble(txtPrice.getText());
        quantity = Integer.parseInt(txtQuantity.getText());
        id = Integer.parseInt(txtId.getText());
        
        Product objproduct = new Product();
        objproduct.setId(id);
        objproduct.setDescription(description);
        objproduct.setEan(ean);
        objproduct.setSku(sku);
        objproduct.setPrice(price);
        objproduct.setQuantity(quantity);
        objproduct.setStatus(status);
        
        ProductDAO objproductdao = new ProductDAO();
        objproductdao.editarProduto(objproduct);
    }//GEN-LAST:event_btnConfirmEditActionPerformed

    private void btnCancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditActionPerformed
            this.setVisible(false);
    }//GEN-LAST:event_btnCancelEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelEdit;
    private javax.swing.JButton btnConfirmEdit;
    private javax.swing.JCheckBox chkStatus;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtEan;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSku;
    // End of variables declaration//GEN-END:variables
}
