package View;


import DAO.ProductDAO;
import Model.Product;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabriel
 */
public class ProductRegister extends javax.swing.JFrame {

    /**
     * Creates new form ProductRegister
     */
    public ProductRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEan = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        btnConfirmRegister = new javax.swing.JButton();
        txtSku = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnCancelRegister = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 770));
        setUndecorated(true);
        getContentPane().setLayout(null);

        txtEan.setBackground(new java.awt.Color(161, 131, 239));
        txtEan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEan.setForeground(new java.awt.Color(255, 255, 255));
        txtEan.setBorder(null);
        txtEan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEanActionPerformed(evt);
            }
        });
        getContentPane().add(txtEan);
        txtEan.setBounds(30, 480, 980, 70);

        txtDescricao.setBackground(new java.awt.Color(161, 131, 239));
        txtDescricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(255, 255, 255));
        txtDescricao.setBorder(null);
        txtDescricao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(30, 270, 980, 60);

        txtQuantidade.setBackground(new java.awt.Color(161, 131, 239));
        txtQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantidade.setBorder(null);
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(800, 370, 211, 70);

        btnConfirmRegister.setContentAreaFilled(false);
        btnConfirmRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmRegister);
        btnConfirmRegister.setBounds(300, 640, 220, 60);

        txtSku.setBackground(new java.awt.Color(161, 131, 239));
        txtSku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSku.setForeground(new java.awt.Color(255, 255, 255));
        txtSku.setBorder(null);
        txtSku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkuActionPerformed(evt);
            }
        });
        getContentPane().add(txtSku);
        txtSku.setBounds(30, 370, 460, 70);

        txtPrice.setBackground(new java.awt.Color(161, 131, 239));
        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtPrice.setBorder(null);
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrice);
        txtPrice.setBounds(510, 370, 270, 70);

        btnCancelRegister.setContentAreaFilled(false);
        btnCancelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelRegister);
        btnCancelRegister.setBounds(570, 640, 220, 60);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("EAN:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 450, 60, 30);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DESCRIÇÃO:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 240, 140, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("QUANTIDADE:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(800, 340, 160, 30);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PREÇO:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(510, 340, 80, 30);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("SKU:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 340, 60, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Product-Register.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-10, 0, 1170, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtSkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkuActionPerformed

    private void btnConfirmRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmRegisterActionPerformed
        String descricao, ean, sku;
        int quantity;
        double price;
        boolean stats;
        
        descricao = txtDescricao.getText();
        ean = txtEan.getText();
        sku = txtSku.getText();
        quantity = Integer.parseInt(txtQuantidade.getText());
        price = Double.parseDouble(txtPrice.getText());
        stats = true;
        
        Product objproduct = new Product();
        objproduct.setDescription(descricao);
        objproduct.setQuantity(quantity);
        objproduct.setSku(sku);
        objproduct.setPrice(price);
        objproduct.setEan(ean); 
        objproduct.setStatus(stats);
        
        ProductDAO objproductdao = new ProductDAO();
        objproductdao.cadastrarProduto(objproduct);
    }//GEN-LAST:event_btnConfirmRegisterActionPerformed

    private void btnCancelRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegisterActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelRegisterActionPerformed

    private void txtEanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelRegister;
    private javax.swing.JButton btnConfirmRegister;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEan;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtSku;
    // End of variables declaration//GEN-END:variables
}
